{% set version = "0.4.4" %}

package:
  name: bmi-tester
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-tester/archive/v{{ version }}.tar.gz
  sha256: e6bf1ddc2a970b82a024814cf17130130e3d5ff1d9ede0b01532d8dffbd14ff5

build:
  number: 0
  noarch: python
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python >=3
    - numpy
    - pytest
    - cfunits
    - standard_names
    - scripting
    - model_metadata
    - click

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test --help

about:
  home: http://github.com/csdms/bmi-tester
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Test Python model implementations of the Basic Model Interface
  description: |
    The bmi_tester package provides a command-line utility for
    testing Python classes that implement the Basic Model Interface
    (BMI). bmi_tester also provides a Python interface to the tester
    that allows users to run tests programmatically.
  doc_url: http://bmi-tester.readthedocs.io/en/latest/
  dev_url: http://github.com/csdms/bmi-tester

extra:
  recipe-maintainers:
    - mcflugen
    - mdpiper
