travis:
  secure:
    BINSTAR_TOKEN: Ycg6OssB3/AsOZjiVTIOfg6LXGBuBpuA+u2F5bO6wP9mMS5mqIvJVUVe36g/fX/LCKU3qVvropWE6GkwJTX56GBxFzJ3o7PSQILsqKXA2CUFfhVhkTIec+PH/mCTRgezTxSiqIrRNQVddyZ3Baef4rBBOhK0Bx4Qf7c2lwGAezbVSxBLKGC7Qa0UmDTwkWpqRcJRsFfRwIHfiTVKqkF0/alBRTLQrI8aYkEn4mY2lgT5J1VeDBiiN6lCSBrjTSy/SVgkfo9u9EZbl1ljnCPXh6cL72M1D7XwsVmvzLMCnHmNQ/zmmlbT0IYuHxGVzuy7X+ZE24HmSYjeLpuGrhAZsNZxEDHqPAzxQT0XddSDuIVDisdpMzqaytFamaVAv2cir86qMcJS3hYlnP/bf5h7yQtERIYKPV8fYdbEDFP6rJTxC7zV+IlcyTi53aSaTL88bRmzfEEAXJPwWeQa9v44NhBqyDKufx7PRXjlVmjLImu+rJImJpzYSw7cZksu5+HH9EvnuX3l7tpwL2lbixQjNeL+u/SragU0c5j+Ouyv1qHeEYdV2ZsLb8el/EyQlyWoKqEnDjD1q/wUkxtBZE7MYV8LZ2aKk5yJhZRXHSYzX9g4bQCmiNNruDMARFMDnQcNm6kM3I1RbW7ksha0o0NFAtGwEphu0UOyO6OWi4bjEA4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
